version: '3.9'
services:
  web:
    image: mpherg/blynk-server:latest
    container_name: blynk
    restart: always
    ports:
      - ${HTTP_PORT}:8080
      - ${HTTPS_PORT}:8441
      - ${WS_PORT}:9443
    networks:
      - default
    volumes:
      - data:/var/data

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
